### ISSUE TITLE
Rumble support

### ISSUE THREAD

**Issue by nsfm** [nsfm/dualsense-ts#54]
** Is your feature request related to a problem? Please describe. **
The controller has a feature that doesn't work with this library

** Describe the solution you'd like **
Support for all available features

**Comment by CaptainThrillsDev** [comment]
Is there any progress on rumble support by chance?

**Comment by nsfm** [comment]
@CaptainThrillsDev Not yet unfortunately. There's a bit of code stubbed out under `src/hid/command.ts` that describes how the command packets are structured (credit to the python library and linux driver) but I never got around to deciding what the API should look like on this end.

I've been interested again lately so I'm up for spending some time on it. Just started a new branch to wrap up gyro/accelerometer support but I'll switch tracks for a bit and see if I can get this going.

I'll work on it this week and share an update by next weekend. If you're interested in giving it a shot I'd also be glad to see a new branch/PR!

**Comment by CaptainThrillsDev** [comment]
I'll keep an eye out for your branch! (I'd love to work on it, but I have no idea where to start, I'm pretty good about picking things up and working with them, but creating from scratch can be a bit difficult)

**Comment by nsfm** [comment]
It went a lot smoother than I hoped, so the branch is already up! #255

**Comment by CaptainThrillsDev** [comment]
Can you publish an alpha version of the rumble support to npm? (Unless the PR is ready for merge). Curious to try it out

**Comment by nsfm** [comment]
@CaptainThrillsDev I still need to work on browser support before I merge unfortunately. I'll try setting up a github action to publish an alpha package from the PR tonight or tomorrow! Could just do it from my laptop but it sounds fun to work into the CI workflow.

If you'd like to try the branch sooner, it should be easy to set up locally (may require at least node v18):
1. Clone the branch
2. `yarn install`
3. `yarn build`

From there, you can use `yarn debug` to run the node test script in this repo's `utils/` directory. Or, if you'd like to import it into your own project, you [can use yalc to publish the package locally](https://www.npmjs.com/package/yalc).
1. `yarn global add yalc`
2. From the root of the dualsense-ts repo, run `yalc publish`
3. From the root of your project, run `yalc add dualsense-ts`

**Comment by SirCaptainTrain** [comment]
Ahh gotcha that makes sense (Easy to forget about the browser side of things when only using the node-hid side)

**Comment by nsfm** [comment]
Running a little late on that, haven't gotten it working in the browser yet. I'll probably settle for releasing a node-hid only version soon.

**Comment by nsfm** [comment]
@CaptainThrillsDev Released rumble support for node-hid on version ^5.1.0 👍
